### ISSUE TITLE
Chromatogram tracing colors on pdf output

### ISSUE THREAD

**Issue by GBardai** [gear-genomics/indigo#1]
Hello,

This is clearly an excellent tool that you have developed for Sanger analysis. My only suggestion so far would be if the colors of the tracings on the pdf file could be more intense and closer to the "standard" dNTPs, please see attached file.

Cheers
Ghalib

[3788.pdf](https://github.com/gear-genomics/indigo/files/3364080/3788.pdf)

**Comment by tobiasrausch** [comment]
Thanks for the suggestion. We changed the PDF colors to A: green, C: blue, G: black and T: red.
