### ISSUE TITLE
The samples.abi file does not work with human genome

### ISSUE THREAD

**Issue by holtgrewe** [gear-genomics/indigo#17]
1. I downloaded the samples.abi file
2. I uploaded it and used both GRCh37 and GRCh38 and clicked analysis
3. I get the error `Error in running Indigo: Couldn't anchor the Sanger trace in the selected reference genome.`

**Comment by tobiasrausch** [comment]
That's how it should be. The example is from zebrafish so you have to select "Danio rerio"
