### ISSUE TITLE
Custom installation

### ISSUE THREAD

**Issue by serge2016** [gear-genomics/indigo#20]
Hello!
Thank you for a great tool!

Could you help me, please, to install and run this package locally? Are there any instructions for this?

**Comment by tobiasrausch** [comment]
The web applications are available at [www.gear-genomics.com](https://www.gear-genomics.com/) and thus, you do not need to install these locally. The backend command-line program [tracy](https://github.com/gear-genomics/tracy) is available via bioconda, as a static binary or as a containerized singularity and docker image.

**Comment by serge2016** [comment]
I know about https://www.gear-genomics.com/indigo/ and already have tested it, thank you!
And my question is about deploying local web-server on my own server for not to upload many sequences to your server...
To be more precise, GUI is not needed for me: I'd prefer to run some kind of batch generation of reports for a set of my ab1 files.

**Comment by tobiasrausch** [comment]
Indigo runs [tracy](https://github.com/gear-genomics/tracy) in the backend.

`tracy decompose ...`

**Comment by serge2016** [comment]
Thank you!!!
