### ISSUE TITLE
BCF file download error

### ISSUE THREAD

**Issue by ipavanellisouza** [gear-genomics/indigo#24]
Hello,

I am trying to call variants from a human gene using ab1 files with indigo web server. 
In the result page every time I've downloaded the bcf file it has errors. The result page seems normal, I can copy and paste the variants in separate file, but the downloaded bcf file does not works.
This is what it looks like my bcf file. 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/16049918/234957052-c8ed960a-acc5-4771-a38b-1dd20f9b68f5.png">

Thanks,

Isabela

**Comment by tobiasrausch** [comment]
It's a binary file. You have to open it with [bcftools](https://github.com/samtools/bcftools).

`bcftools view indigo-variants.bcf`
